apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: hbas3h00y-nodejs
  janus-idp.io/tekton: hbas3h00y-nodejs
  backstage.io/kubernetes-id: hbas3h00y-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hbas3h00y-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
